CREATE ROLE stocks WITH LOGIN PASSWORD 'stocks';

CREATE ROLE stocktracker WITH LOGIN PASSWORD 'stocktracker' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE stocks_database;
GRANT ALL PRIVILEGES ON DATABASE stocks_database TO stocktracker ;
GRANT ALL PRIVILEGES ON DATABASE stocks_database TO stocks;