apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-and-deploy-stock-tracker-services
spec:
  serviceAccountName: stock-tracker-service-account
  pipelineRef:
    name: pipeline-build-and-deploy-services
  params: 
  resources:
    - name: source-repo
      resourceRef:
        name: git-source-stock-tracker  