apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-rest-stock-image
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: context-dir
        description: The context dir of the project containing the maven pom.xml file
        default: stock-tracker-parent-root
  results:
    - name: image-name
      description: Name of the container image                           
  steps: 
    - name: list-project-folder
      image: busybox
      command: ["ls", "-ltr", "/workspace/source/$(inputs.params.context-dir)"]
    - name: build-push-container
      image: docker.io/maven:3.6.3-openjdk-15
      workingDir: "/workspace/source/$(inputs.params.context-dir)/stocks/rest-stocks"
      script: |
         #!/usr/bin/env bash
         # cmd="mvn -ntp clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true"
         cmd="mvn -ntp clean jib:build"
         echo "Command: ${cmd}"
         pwd
         ${cmd}                             
  volumes:
    - name: varlibc
      emptyDir: {}    