version: "3"
services:
    database:
        image: "mysql:latest"
        container_name: "stocks-database"
        ports:
           - "3306:3306"
        environment:
           - MYSQL_ROOT_HOST=%
           - MYSQL_ROOT_PASSWORD=rootpw
           - MYSQL_DATABASE=stocks_database
           - MYSQL_USER=stocktracker
           - MYSQL_PASSWORD=stocktracker     
    rest-stocks:
        image: "quay.io/stocktracker/rest-stocks:1.0"
        container_name: "rest-stocks"
        ports:
           - "8081:8081"
    rest-quotes:
        image: "quay.io/stocktracker/rest-quotes:1.0"
        container_name: "rest-quotes"
        ports:
           - "8082:8082"       
